app = 'just-ingredients-monitoring'
primary_region = 'cdg'

[build]
  dockerfile = 'monitoring/Dockerfile'

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  enable_ha = false
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/-/healthy'