# fly.toml app configuration file generated for just-ingredients-staging on 2025-10-27T15:57:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'just-ingredients-staging'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'
  max_unavailable = 0.0

[env]
  HEALTH_PORT = '8080'
  LOG_FORMAT = 'pretty'
  RUST_LOG = 'info,sqlx=warn'
  TELEGRAM_ENV = 'staging'

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512
